version: '3.8'
services:
    postgres:
        image: bitnami/postgresql:latest
        restart: always
        environment:
          - "POSTGRES_HOST=${POSTGRES_HOST}"
          - "POSTGRES_USER=${POSTGRES_USER}"
          - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
          - "POSTGRES_DATABASE=${POSTGRES_DATABASE}"
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432' 
        volumes:
          # - ./postgres-data:/var/lib/postgresql/data
          - ./sql/000_init.sql:/docker-entrypoint-initdb.d/000_init.sql
          - ./sql/data/001_dimension.sql:/docker-entrypoint-initdb.d/001_dimension.sql
